# Generated by Django 4.2.4 on 2024-04-15 23:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employer",
            options={
                "verbose_name": "funcionário",
                "verbose_name_plural": "funcionários",
            },
        ),
    ]
