# Generated by Django 4.2.4 on 2023-08-18 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="diagnóstico")),
                (
                    "description",
                    models.TextField(
                        default="N/A", max_length=100, verbose_name="descrição"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "diagnóstico",
                "verbose_name_plural": "diagnósticos",
                "db_table": "diagnosis",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nome")),
                ("age", models.IntegerField(verbose_name="idade")),
                (
                    "room",
                    models.CharField(max_length=10, verbose_name="enfermaria/leito"),
                ),
                ("medical_record", models.IntegerField(verbose_name="prontuário")),
                (
                    "hospitalized_in",
                    models.DateField(verbose_name="data da internação"),
                ),
                ("sorted_in", models.DateField(verbose_name="data da triagem")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="patient.diagnosis",
                        verbose_name="diagnóstico",
                    ),
                ),
            ],
            options={
                "verbose_name": "paciente",
                "verbose_name_plural": "pacientes",
                "db_table": "patient",
            },
        ),
    ]
