# Generated by Django 4.2.4 on 2023-10-26 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="diagnóstico")),
                (
                    "description",
                    models.TextField(
                        default="N/A", max_length=100, verbose_name="descrição"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "diagnóstico",
                "verbose_name_plural": "diagnósticos",
                "db_table": "diagnosis",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="nome completo"),
                ),
                ("age", models.IntegerField(verbose_name="idade")),
                ("medical_record", models.IntegerField(verbose_name="prontuário")),
                (
                    "hospitalized_in",
                    models.DateField(verbose_name="data da internação"),
                ),
                ("sorted_in", models.DateField(verbose_name="data da triagem")),
                (
                    "nutritional_route",
                    models.CharField(max_length=100, verbose_name="via nutricional"),
                ),
                (
                    "eligible",
                    models.BooleanField(default=False, verbose_name="elegível"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "paciente",
                "verbose_name_plural": "pacientes",
                "db_table": "patient",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ward", models.CharField(max_length=10, verbose_name="enfermaria")),
                ("bed", models.PositiveSmallIntegerField(verbose_name="leito")),
            ],
            options={
                "verbose_name": "quarto",
                "verbose_name_plural": "quartos",
                "db_table": "room",
            },
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("ward", "bed"), name="unique_room"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="diagnoses",
            field=models.ManyToManyField(
                related_name="patients",
                to="patient.diagnosis",
                verbose_name="diagnósticos",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="room",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient",
                to="patient.room",
                verbose_name="quarto",
            ),
        ),
    ]
