# Generated by Django 5.0.7 on 2024-09-16 22:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diagnosis",
            options={
                "ordering": ("name",),
                "verbose_name": "diagnóstico",
                "verbose_name_plural": "diagnósticos",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ("ward", "bed"),
                "verbose_name": "quarto",
                "verbose_name_plural": "quartos",
            },
        ),
    ]
