# Generated by Django 4.2.4 on 2023-08-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="released",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="patient",
            name="name",
            field=models.CharField(max_length=100, verbose_name="nome completo"),
        ),
    ]
