# Generated by Django 4.2.4 on 2023-10-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("ward", "bed"), name="unique_room"
            ),
        ),
    ]
