# Generated by Django 4.2.4 on 2023-08-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0002_patient_released_alter_patient_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="released",
            field=models.BooleanField(default=False, verbose_name="alta médica"),
        ),
    ]
