# Generated by Django 4.2.4 on 2023-10-23 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ventilation_mode",
                    models.CharField(max_length=100, verbose_name="modo ventilatório"),
                ),
                (
                    "initial_nutritional_route",
                    models.CharField(
                        max_length=100, verbose_name="via nutricional inicial"
                    ),
                ),
                (
                    "actual_nutritional_route",
                    models.CharField(
                        max_length=100, verbose_name="via nutricional atual"
                    ),
                ),
                (
                    "treatment",
                    models.CharField(max_length=100, verbose_name="atendimento"),
                ),
                ("conduct", models.TextField(max_length=100, verbose_name="conduta")),
                (
                    "observation",
                    models.TextField(
                        default="N/A", max_length=100, verbose_name="observação"
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="patient.patient",
                        verbose_name="paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "relatório",
                "verbose_name_plural": "relatórios",
                "db_table": "report",
            },
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                fields=("patient", "created_at"), name="unique_patient_per_day"
            ),
        ),
    ]
