# Generated by Django 4.2.4 on 2023-08-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0001_initial"),
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="conduct",
            field=models.TextField(max_length=100, verbose_name="conduta"),
        ),
        migrations.AlterUniqueTogether(
            name="report",
            unique_together={("patient", "created_at")},
        ),
    ]
