# Generated by Django 4.2.4 on 2024-03-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="observation",
            field=models.TextField(
                default="N/A", max_length=255, verbose_name="observação"
            ),
        ),
    ]
