# Generated by Django 4.2.4 on 2023-08-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0002_alter_report_conduct_alter_report_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="criado em"),
        ),
        migrations.AlterField(
            model_name="report",
            name="updated_at",
            field=models.DateField(auto_now=True, verbose_name="atualizado em"),
        ),
    ]
