# Generated by Django 5.0.7 on 2024-07-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0002_alter_report_observation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
        ),
        migrations.AlterField(
            model_name="report",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
        ),
    ]
