# Generated by Django 5.0.7 on 2024-09-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0003_alter_report_created_at_alter_report_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="criado em"),
        ),
    ]
