name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SECRET_KEY: git-x*8k_n95!c^l!5(zbbc9fi0h!x9ze!yii2nvbi*&xz8mfuns51
  DEBUG: True
  ALLOWED_HOSTS: 127.0.0.1, localhost
  CORS_ALLOWED_ORIGINS: http://localhost:3000, http://127.0.0.1:3000
  CSRF_TRUSTED_ORIGINS: http://localhost:3000, http://127.0.0.1:3000


jobs:
  build-test-coverage:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Create Coverage
      run: |
        coverage run --data-file=".github/coverage/.coverage" --source='.' manage.py test
        coverage xml --data-file=".github/coverage/.coverage" -o .github/coverage/coverage.xml
    - name: Get Coverage
      uses: orgoro/coverage@v3.1
      with:
        coverageFile: .github/coverage/coverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}
